# Builds the project and places the results in the "gh-pages" branch, which will be shown by github.io
name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install and Build 
      
        run: |
          npm install
          npm run build-prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.9
        with:
          branch: gh-pages
          folder: dist